name: Deploy Microservices:DB-CRUD to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-u-costos:
    name: Deploy u-costos-876701
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy u-costos \
            --source ./u-costos \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-u-conversacion:
    name: Deploy u-conversacion-228911
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy u-conversacion \
            --source ./u-conversacion \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-u-base:
    name: Deploy u-base-870666
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy u-base \
            --source ./u-base \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-c-costos:
    name: Deploy c-costos-897646
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy c-costos \
            --source ./c-costos \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-c-base:
    name: Deploy c-base-295319
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy c-base \
            --source ./c-base \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-c-conversacion:
    name: Deploy c-conversacion-810688
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy c-conversacion \
            --source ./c-conversacion \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI
  deploy-r-base:
    name: Deploy r-base-123113
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        env:
          AMQP_URL: ${{ secrets.AMQP_URL }}
          PUERTO: ${{ secrets.PUERTO }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud run deploy r-base \
            --source ./r-base \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances=1 \
            --cpu=1 \
            --memory=512Mi \
            --set-env-vars AMQP_URL=$AMQP_URL,PUERTO=$PUERTO,MONGO_URI=$MONGO_URI